spring.application.name=usuario
spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

# ===================================================================
# CONFIGURACIÓN DINÁMICA DE BASE DE DATOS (MIGRACIÓN DOCKER/LOCAL)
# ===================================================================
# Se cambia 'localhost' por la IP privada de la EC2 para que Docker pueda conectar
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://172.31.17.116:3306/full_stack_usuario?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:full_stack_1}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Tav_2026.@}

# Corrección de Drivers: Se cambia el driver de Postgres a MySQL
spring.datasource.driver-class-name=${SPRING_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Corrección de Dialecto: Se cambia el dialecto de Postgres a MySQL
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.MySQLDialect}
# ===================================================================

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# Puerto interno donde corre el Microservicio
server.port=5000

springdoc.swagger-ui.path=/usuario.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operations-sorter=Alpha
app.name=Gestion de usuarios
app.version=3.0.0