name: Deploy Microservice to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        username: [ubuntu, ec2-user] # Probará ambos usuarios automáticos para asegurar la entrada
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ matrix.username }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "app" ]; then
              git clone https://github.com/${{ github.repository }}.git app
              cd app
            else
              cd app
              git pull origin main
            fi
            docker compose down
            docker compose up --build -d